version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile-jenkins
    container_name: jenkins-controller
    ports:
      - "8082:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home01:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

